lab2 added
dmkrch/dmkrch.github.io pull request #1
Opened 2022-03-12 12:02 UTC by dmkrch

pdf file attached with ux, html prototypes

2022-03-16 17:46 UTC, Nastik1811 commented
А где описание проекта?

2022-03-17 19:09 UTC, Nastik1811 requested changes
Where is a project description?

2022-03-31 19:00 UTC, dmkrch commented
added description for future functional of app
see .pdf file with ux prototype

2022-04-01 13:15 UTC, Nastik1811 approved these changes
Ok, `8`

2022-04-01 15:13 UTC, merged